### ISSUE TITLE
why in the universe was this made....

### ISSUE THREAD

**Issue by SolveAllProblemsRightNow** [CodeSelfStudy/Copy-YouTube-Video-Titles#1]
why in the universe was this made....

**Comment by j127** [comment]
To solve a very specific problem. :)

**Comment by SolveAllProblemsRightNow** [comment]
what problem was that? 

i dont understand how this helps most of society & humanity?

**Comment by j127** [comment]
> i dont understand how this helps most of society & humanity?

It doesn't help most of society and humanity -- it solves a _very_ specific problem, which is to do exactly what the description says. :)

**Comment by SolveAllProblemsRightNow** [comment]
this isn't solving any specific problems that other things already solved

what is this doing that nothing else does?

what value is this adding to society and humanity by the problem it solves? 

what good are you doing in the world by adding clutter onto the already cluttered extensions out there

**Comment by j127** [comment]
I know that there are other ways to do this, but it's something that was useful to a few people for performing a certain task at a certain time. I don't think anyone is using it now. I'm going to close this issue, since the project is inactive now. :)
